### ISSUE TITLE
uper_open_type_skip bug

### ISSUE THREAD

**Issue by johnhypo** [mouse07410/asn1c#129] opened 2023-05-10 04:47 UTC
Look at comment in code. Help!

```
int
uper_open_type_skip(asn_codec_ctx_t *ctx, asn_per_data_t *pd) {
	asn_TYPE_descriptor_t s_td;
	asn_dec_rval_t rv;

	s_td.name = "<unknown extension>";
//s_td not initiallized, this  assignment statement crashes.
//it occured while I use asn1c to parse PDU MultimediaSystemControlMessage
//refer to https://github.com/vlm/asn1c/issues/475
	s_td.op->uper_decoder = uper_sot_suck;

	rv = uper_open_type_get(ctx, &s_td, 0, 0, pd);
	if(rv.code != RC_OK)
		return -1;
	else
		return 0;
}
```

**Comment by mouse07410** [comment] 2023-06-15 13:29
This is probably beyond my competency - but there's no need to "initialize" anything there, IMHO.

`asn_TYPE_descriptor_t` is a structure with a field `name` that is a pointer to a string.  The code assigns to it a pointer to `"<unknown_extension>"`. I don't see a problem there, from C point of view.

Perhaps, with more information (like OS, compiler, etc.) and a minimal reproducer, I could try to dig deeper...?

**Comment by johnhypo** [comment] 2023-06-15 13:29
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by mouse07410** [comment] 2023-12-25 03:36
Since I don't know what to do with this issue, sorry to say I'm closing it. Please re-open if you have anything to add that would make it easier to determine what's wrong and how to fix it.

**Closed as completed by mouse07410** 2023-12-25 03:36 UTC
